package dcs.aber.ac.uk.csm2020_group_3.RecommendationSystem;

import java.util.ArrayList;

/**
 * Class that sorts modules - from those selected in UI to those from Generators - and stores them.
 * (not modules stored in DB)
 */
public class ModuleSorter {

    public static Integer previousModuleAmount;
    public static Integer currentModuleAmount;
    public static ArrayList<Integer> creditsPerYear;

    public ModuleSorter (){
        this.year0Modules = new ArrayList<>();
        this.year1Modules = new ArrayList<>();
        this.year2Modules = new ArrayList<>();
        this.year3Modules = new ArrayList<>();
        this.year4Modules = new ArrayList<>();

    }

    public ArrayList<ModuleInfo> year0Modules;
    public ArrayList<ModuleInfo> year1Modules;
    public ArrayList<ModuleInfo> year2Modules;
    public ArrayList<ModuleInfo> year3Modules;
    public ArrayList<ModuleInfo> year4Modules;


    /**
     * Sorts modules generated by CoreListGenerators, or provided by UI.
     * Overloaded method that works on singular or a list of ModuleInfo objects.
     */
    public void sortModules(ModuleInfo module) {

        // check year and then append to respective list
        if (module.getModuleYear() == 0) {
            year0Modules.add(module);
        }
        if (module.getModuleYear() == 1) {
            year1Modules.add(module);
        }
        if (module.getModuleYear() == 2) {
            year2Modules.add(module);
        }
        if (module.getModuleYear() == 3) {
            year3Modules.add(module);
        }
        if (module.getModuleYear() == 4) {
            year4Modules.add(module);
        }
    }
    public void sortModules(ArrayList<ModuleInfo> modules) {
        // iterate through list of module info items
        for (ModuleInfo module : modules) {

            // check year and then append to respective list
            if (module.getModuleYear() == 0) {
                year0Modules.add(module);
            }
            if (module.getModuleYear() == 1) {
                year1Modules.add(module);
            }
            if (module.getModuleYear() == 2) {
                year2Modules.add(module);
            }
            if (module.getModuleYear() == 3) {
                year3Modules.add(module);
            }
            if (module.getModuleYear() == 4) {
                year4Modules.add(module);
            }
        }
    }

}
