package dcs.aber.ac.uk.csm2020_group_3.RecommendationSystem;

import java.util.ArrayList;
import java.util.Collections;

/**
 * Class that sorts modules - from those selected in UI to those from Generators - and stores them.
 * (not modules stored in DB)
 */
public abstract class ModuleHandler {

    public static Integer previousModuleAmount;
    public static Integer currentModuleAmount;
    public static ArrayList<Integer> creditsPerYear;

    public ModuleHandler(){
        year0Modules = new ArrayList<>();
        year1Modules = new ArrayList<>();
        year2Modules = new ArrayList<>();
        year3Modules = new ArrayList<>();
        year4Modules = new ArrayList<>();

    }

    public static ArrayList<Module> year0Modules;
    public static ArrayList<Module> year1Modules;
    public static ArrayList<Module> year2Modules;
    public static ArrayList<Module> year3Modules;
    public static ArrayList<Module> year4Modules;


    /**
     * Sorts modules generated by CoreListGenerators, or provided by UI.
     * Overloaded method that works on singular or a list of Module objects.
     */
    public void sortModules(Module module) {

        // check year and then append to respective list
        if (module.getYear() == 0) {
            year0Modules.add(module);
        }
        if (module.getYear() == 1) {
            year1Modules.add(module);
        }
        if (module.getYear() == 2) {
            year2Modules.add(module);
        }
        if (module.getYear() == 3) {
            year3Modules.add(module);
        }
        if (module.getYear() == 4) {
            year4Modules.add(module);
        }
    }
    public void sortModules(ArrayList<Module> modules) {
        // iterate through list of module info items
        for (Module module : modules) {

            // check year and then append to respective list
            if (module.getYear() == 0) {
                year0Modules.add(module);
            }
            if (module.getYear() == 1) {
                year1Modules.add(module);
            }
            if (module.getYear() == 2) {
                year2Modules.add(module);
            }
            if (module.getYear() == 3) {
                year3Modules.add(module);
            }
            if (module.getYear() == 4) {
                year4Modules.add(module);
            }
        }
    }



    public void moveModuleToSelectedList(){
        ;
    }

}
